### ISSUE TITLE
Extension fails to load when the gem is in a group

### ISSUE THREAD

**Issue by aidalgol** [middleman/middleman-livereload#101]
I have a project with the `Gemfile`
```
gem "middleman", "~> 4.2"
gem "middleman-livereload", "~> 3.4", group: :development
```
And my Middleman `config.rb` includes the line `activate :livereload`.  When I run `bundler exec middleman server`, I get the following error.
```
bundler: failed to load command: middleman (/home/aidan/.rbenv/versions/2.5.1/bin/middleman)
RuntimeError: Unknown Extension: livereload. Check the name and make sure you have referenced the extension's gem in your Gemfile.
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:86:in `load'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/extension_manager.rb:51:in `activate'
  /home/aidan/src/lfgd-site/config.rb:24:in `block in evaluate_configuration!'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:58:in `instance_exec'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:58:in `block in execute'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:58:in `execute'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:289:in `initialize'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
  /home/aidan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
  /home/aidan/.rbenv/versions/2.5.1/bin/middleman:23:in `load'
  /home/aidan/.rbenv/versions/2.5.1/bin/middleman:23:in `<top (required)>'
```

If I comment out `, group: :development` on the `middleman-livereload` line in the `Gemfile`, middleman runs just fine, and live reloading works.
(I am running Ruby version 2.5.1 through rbenv.)

**Comment by aidalgol** [comment]
This is still happening with middleman-livereload 3.4.6.

**Comment by Momus** [comment]
> This is still happening with middleman-livereload 3.4.6 (and middleman 4.3).
Can confirm for middleman 4.3.5

**Comment by SteveBenner** [comment]
Can confirm this occurs in `middleman 4.3.7`
