### ISSUE TITLE
SocketError with MM 3.0.14 and MM-LR 3.1.0

### ISSUE THREAD

**Issue by dannyprose** [middleman/middleman-livereload#32]
I apologize if this has been addressed somewhere else, but I've been having this error for a while and have been just working around it. More frustrating is that it is occurring on only one of two environments that are essentially the same. Posting here instead of the forums just in case, but will cross-post there.

Whenever I activate Middleman-Livereload, I _always_ recieve the following error, even with fresh gemsets:

```
SocketError at /
getaddrinfo: nodename nor servname provided, or not known

Ruby    $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb: in initialize, line 762
Web GET 127.0.0.1/
```

In the terminal:

```
#<SocketError: getaddrinfo: nodename nor servname provided, or not known>
SocketError: getaddrinfo: nodename nor servname provided, or not known
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `initialize'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `open'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `connect'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:744:in `start'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1284:in `request'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1264:in `send_request'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:46:in `use_vendored?'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:97:in `livereload_source'
  (erb):14:in `block (2 levels) in process!'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in `eval'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/erb.rb:838:in `result'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:74:in `block (2 levels) in process!'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:74:in `gsub!'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:74:in `block in process!'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:72:in `each'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload/body_processor.rb:72:in `process!'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload.rb:28:in `_call'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-livereload-0.3.14/lib/rack/livereload.rb:14:in `call'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
  $/.rvm/gems/ruby-1.9.3-p194@thinktank/gems/rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  $/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

Gemfile:

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (3.2.13)
      i18n (= 0.6.1)
      multi_json (~> 1.0)
    chunky_png (1.2.8)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.3.3)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    em-websocket (0.5.0)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.5.3)
    eventmachine (1.0.3)
    execjs (1.4.0)
      multi_json (~> 1.0)
    favicon_maker (0.2.1)
      mini_magick (~> 3.5)
    fssm (0.2.10)
    haml (4.0.3)
      tilt
    hike (1.2.2)
    http_parser.rb (0.5.3)
    http_router (0.10.2)
      rack (>= 1.0.0)
      url_mount (~> 0.2.1)
    i18n (0.6.1)
    listen (0.7.3)
    maruku (0.6.1)
      syntax (>= 1.0.0)
    middleman (3.0.14)
      middleman-core (= 3.0.14)
      middleman-more (= 3.0.14)
      middleman-sprockets (~> 3.1.0)
    middleman-core (3.0.14)
      activesupport (~> 3.2.6)
      bundler (~> 1.1)
      listen (~> 0.7.3)
      rack (~> 1.4.1)
      rack-test (~> 0.6.1)
      rb-fsevent (~> 0.9.3)
      thor (~> 0.15.4)
      tilt (~> 1.3.6)
    middleman-favicon-maker (3.2)
      favicon_maker (~> 0.2.0)
      middleman-core (>= 3.0.0)
    middleman-livereload (3.1.0)
      em-websocket (>= 0.2.0)
      middleman-core (>= 3.0.2)
      multi_json (~> 1.0)
      rack-livereload
    middleman-more (3.0.14)
      coffee-script (~> 2.2.0)
      coffee-script-source (~> 1.3.3)
      compass (>= 0.12.2)
      execjs (~> 1.4.0)
      haml (>= 3.1.6)
      i18n (~> 0.6.0, < 0.6.2)
      maruku (~> 0.6.0)
      middleman-core (= 3.0.14)
      padrino-helpers (= 0.10.7)
      sass (>= 3.1.20)
      uglifier (~> 1.2.6)
    middleman-sprockets (3.1.1)
      middleman-core (>= 3.0.14)
      padrino-helpers (= 0.10.7)
      sprockets (~> 2.1)
      sprockets-helpers (~> 1.0.0)
      sprockets-sass (~> 1.0.0)
    mini_magick (3.6.0)
      subexec (~> 0.2.1)
    multi_json (1.7.3)
    padrino-core (0.10.7)
      activesupport (~> 3.2.0)
      http_router (~> 0.10.2)
      sinatra (~> 1.3.1)
      thor (~> 0.15.2)
      tilt (~> 1.3.0)
    padrino-helpers (0.10.7)
      i18n (~> 0.6)
      padrino-core (= 0.10.7)
    rack (1.4.5)
    rack-livereload (0.3.14)
      rack
    rack-protection (1.5.0)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rb-fsevent (0.9.3)
    redcarpet (3.0.0)
    sass (3.2.9)
    sinatra (1.3.6)
      rack (~> 1.4)
      rack-protection (~> 1.3)
      tilt (~> 1.3, >= 1.3.3)
    sprockets (2.9.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.0.1)
      sprockets (~> 2.0)
    sprockets-sass (1.0.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    subexec (0.2.3)
    susy (1.0.8)
      compass (>= 0.12.2)
      sass (>= 3.2.0)
    syntax (1.0.0)
    thor (0.15.4)
    tilt (1.3.7)
    uglifier (1.2.7)
      execjs (>= 0.3.0)
      multi_json (~> 1.3)
    url_mount (0.2.1)
      rack

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 3.0.5)
  middleman-favicon-maker
  middleman-livereload
  redcarpet
  susy (~> 1.0.5)
```

Any help is really welcome - I have gone down a ton of paths to try and figure this out. I can also provide any additional details.

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*
