### ISSUE TITLE
multi_json conflicts prevent activation of livereload

### ISSUE THREAD

**Issue by karland** [middleman/middleman-livereload#57]
Hi, when I am running `middleman init` I get multi_json conflicts (see below). 

I can fix this by removing 
`gem uninstall multi_json --version 1.9.2` and afterwards
`gem uninstall multi_json --version 1.9.0` so that only 
`multi_json 1.8.4` remains, but the newer versions of `multi_json` are quickly re-installed. Can you help? Thanks.

```
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate middleman-livereload-3.2.1, because multi_json-1.9.2 conflicts with multi_json (~> 1.8.4) (Gem::LoadError)
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1262:in `activate'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:196:in `rescue in try_activate'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:193:in `try_activate'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:144:in `require'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/extensions.rb:71:in `block in load_extensions_in_path'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/extensions.rb:70:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/extensions.rb:70:in `load_extensions_in_path'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/lib/middleman-core/load_paths.rb:40:in `setup_load_paths'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/middleman-core-3.2.2/bin/middleman:10:in `<top (required)>'
    from C:/Ruby193/bin/middleman:23:in `load'
    from C:/Ruby193/bin/middleman:23:in `<main>'
```

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

*(this repo is maintained by a few people contributing their free time, unfortunately we can't solve every issue on our own, so help from others is needed for some of the more exotic issues that crops up)*
