### ISSUE TITLE
Exception while processing events: undefined local variable or method `ignore_manager'

### ISSUE THREAD

**Issue by borisrorsvort** [middleman/middleman-livereload#93]
Happening since middleman v4 after a file change

```
[2016-07-13T18:30:05.778676 #10356] ERROR -- : exception while processing events: undefined local variable or method `ignore_manager' for #<Middleman::Application:0x47273526040900> Backtrace:
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/extension_3_1.rb:35:in `block (2 levels) in initialize'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:264:in `call'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:264:in `block (2 levels) in changed'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:264:in `each'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:264:in `block in changed'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:348:in `call'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:348:in `block in run_callbacks'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:341:in `run_callbacks'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources.rb:331:in `did_change'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `instance_exec'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `block in execute'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `each'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hamster-2.0.0/lib/hamster/vector.rb:431:in `each'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:51:in `execute'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources/source_watcher.rb:256:in `update'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0/lib/middleman-core/sources/source_watcher.rb:219:in `on_listener_change'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `call'
 -- /home/boris/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

```

**Comment by chenware** [comment]
experiencing the same

**Comment by chenware** [comment]
Was using an older version of the gem with middleman 4. Upgrading made the error go away.

**Comment by tdreyno** [comment]
^
